project_id = "mzqpvnxtwshjcyzaipea"

[functions.auth-email-hook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-booking]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.sms-2fa]
verify_jwt = false

[functions.admin-gen-link]
verify_jwt = false

[functions.phone-login]
verify_jwt = false

[functions.member-family]
verify_jwt = false

[functions.place-search]
verify_jwt = false

[functions.booking-status]
verify_jwt = false
