// Shared brand tokens for Apexia VIP auth emails.
// Note: Body background must remain white; the dark aesthetic lives inside the inner card.

export const brand = {
  siteName: 'APEXIA VIP',
  champagne: '#a68d5c',
  champagneMuted: '#8a7448',
  ink: '#0a0a0a',
  panel: '#000000',
  panelBorder: '#1a1a1a',
  textLight: '#e6ddd1',
  textMuted: '#8a8578',
  hairline: '#2a2620',
}

export const styles = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: "'Inter', Arial, sans-serif",
    padding: '32px 0',
    margin: 0,
  } as const,
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    padding: '0',
  } as const,
  panel: {
    backgroundColor: brand.panel,
    border: `1px solid ${brand.panelBorder}`,
    padding: '56px 48px',
    textAlign: 'center' as const,
  } as const,
  brandMark: {
    color: brand.champagne,
    fontFamily: "'Cormorant Garamond', Georgia, serif",
    fontSize: '20px',
    letterSpacing: '0.4em',
    fontWeight: 400,
    margin: '0 0 4px',
    textTransform: 'uppercase' as const,
  } as const,
  rule: {
    borderTop: `1px solid ${brand.hairline}`,
    width: '40px',
    margin: '24px auto 32px',
  } as const,
  h1: {
    color: brand.textLight,
    fontFamily: "'Cormorant Garamond', Georgia, serif",
    fontSize: '28px',
    fontWeight: 300,
    letterSpacing: '0.08em',
    margin: '0 0 24px',
    textAlign: 'center' as const,
  } as const,
  text: {
    color: brand.textLight,
    fontSize: '14px',
    lineHeight: '1.7',
    letterSpacing: '0.03em',
    margin: '0 0 20px',
    textAlign: 'center' as const,
    fontWeight: 300,
  } as const,
  link: { color: brand.champagne, textDecoration: 'none' } as const,
  button: {
    backgroundColor: 'transparent',
    color: brand.champagne,
    fontSize: '11px',
    letterSpacing: '0.3em',
    textTransform: 'uppercase' as const,
    borderRadius: '2px',
    border: `1px solid ${brand.champagne}`,
    padding: '16px 36px',
    textDecoration: 'none',
    display: 'inline-block',
    margin: '12px 0 8px',
    fontWeight: 400,
  } as const,
  code: {
    fontFamily: "'Courier New', Courier, monospace",
    fontSize: '26px',
    letterSpacing: '0.5em',
    color: brand.champagne,
    margin: '8px 0 24px',
    textAlign: 'center' as const,
  } as const,
  footer: {
    color: brand.textMuted,
    fontSize: '11px',
    letterSpacing: '0.1em',
    margin: '32px 0 0',
    textAlign: 'center' as const,
    lineHeight: '1.6',
  } as const,
  legal: {
    color: '#5a564d',
    fontSize: '10px',
    letterSpacing: '0.2em',
    textTransform: 'uppercase' as const,
    margin: '24px 0 0',
    textAlign: 'center' as const,
  } as const,
}
